### ISSUE TITLE
ros2cs on .spec file gets "Unable to parse field defined as 'FieldDeclaration'..."

### ISSUE THREAD

**Issue by sedwick2048** [noelex/rclnet#11] opened 2024-04-30 20:07 UTC
I'm trying to follow [the instructions](https://github.com/noelex/rclnet?tab=readme-ov-file), but when I get to the part about running the ros2cs utility on the ros2cs.spec file in my Visual Studio project, I see in both the admin command prompt, admin PowerShell:

Searching in directory: C:\dev\ROS2cs\install
Searching in directory: C:\dev\ros2_humble
Unable to parse field defined as 'FieldDeclaration { Type = bool, Identifier = bool_values_default, Value = [false, true, false], IsArray = True, ArrayLength = 3, InlineComment = , IsUpperBounded = False }': Unexpected boolean value ' true'.

I also ran it from both kinds of command prompts available from Visual Studio 2022, which failed the same way after the "install" line.  I can't find much about this online, closest is something about JavaScript.  Which bit of code is this and what could be happening?  Thanks...

**Comment by noelex** [comment] 2024-05-01 02:43
Do you have a `msg` file which defines a field `bool_values_default` of type `bool[]`?

You can try editing this file and modify the default value of the field `bool_values_default` to `[false,true,false]` and see if that works.

**Comment by sedwick2048** [comment] 2024-05-01 17:59
There is one .msg file (not including .msg.stamp) in my rclnet folder where I cloned that repo.  I didn't consciously create it (or any .msg files) and its text does not include "bool_values_default":
C:\Dev\rclnet\examples\custom_msgs\msg\MyMessage.msg

There are 514 such files in my ROS2cs folder; 16 of them have "bool_values_default" in them:
X C:\Dev\ROS2cs\build\test_msgs\rosidl_cmake\srv\Arrays_Request.msg
X C:\Dev\ROS2cs\build\test_msgs\rosidl_cmake\srv\Arrays_Response.msg
X C:\Dev\ROS2cs\install\share\test_interface_files\msg\Arrays.msg
Y C:\Dev\ROS2cs\install\share\test_interface_files\msg\BoundedPlainSequences.msg
Y C:\Dev\ROS2cs\install\share\test_interface_files\msg\BoundedSequences.msg
Z C:\Dev\ROS2cs\install\share\test_interface_files\msg\UnboundedSequences.msg
X C:\Dev\ROS2cs\install\share\test_msgs\msg\Arrays.msg
Y C:\Dev\ROS2cs\install\share\test_msgs\msg\BoundedPlainSequences.msg
Y C:\Dev\ROS2cs\install\share\test_msgs\msg\BoundedSequences.msg
Z C:\Dev\ROS2cs\install\share\test_msgs\msg\UnboundedSequences.msg
X C:\Dev\ROS2cs\install\share\test_msgs\srv\Arrays_Request.msg
X C:\Dev\ROS2cs\install\share\test_msgs\srv\Arrays_Response.msg
X C:\Dev\ROS2cs\src\ros2\test_interface_files\msg\Arrays.msg
Y C:\Dev\ROS2cs\src\ros2\test_interface_files\msg\BoundedPlainSequences.msg
Y C:\Dev\ROS2cs\src\ros2\test_interface_files\msg\BoundedSequences.msg
Z C:\Dev\ROS2cs\src\ros2\test_interface_files\msg\UnboundedSequences.msg

The letter before each file above indicates the line it contains:
X: bool[3] bool_values_default [false, true, false]
Y: bool[<=3] bool_values_default [false, true, false]
Z: bool[] bool_values_default [false, true, false]

Which file should I modify?  Thanks...

**Comment by noelex** [comment] 2024-05-01 21:41
Exclude these files from code generation by adding the following line to your `ros2cs.spec` file if you don’t need them:
```
exclude test_interface_files test_msgs
```

**Comment by sedwick2048** [comment] 2024-05-02 13:58
The error still happens.

**Comment by noelex** [comment] 2024-05-02 14:11
Are you seeing the same error message? Could you please post the output of ros2cs here?

**Comment by noelex** [comment] 2024-05-02 14:15
Please also post the content of the `ros2cs.spec` you’re currently using.

**Comment by sedwick2048** [comment] 2024-05-02 14:18
These are the only lines not commented:

```
output ./
namespace Rosidl.Messages
from-ament-index
exclude test_interface_files test_msgs
```

It wouldn't have anything to do with that space in the `Unexpected boolean value ' true'`, would it?  It seems to know it's a boolean, so probably not, but...

**Comment by noelex** [comment] 2024-05-02 14:39
There is bug within ros2cs where it can’t handle default value of array which contains spaces before or after array elements.

To work around this issue, you can:

1. Make sure that there’s no space before or after elements of arrays.
2. Do not perform code generation for message files triggering this bug.

In this case I recommend 2, because `test_interface_files` and `test_msgs` are just used for testing and are safe to ignore.

I’m not sure what’s inside the directory `C:\dev\ROS2cs` but I guess it contains the source code of ROS2? If so then you can try replace `from-ament-index` with `from-directory C:\dev\ros2_humble ` so that ros2cs can skip code generation for all messages defined in the source code directory.

**Comment by sedwick2048** [comment] 2024-05-02 14:45
ros2cs contains the contents of [this Git repo](https://github.com/RobotecAI/ros2cs/tree/develop).

I made the replacement and the next run spit out this:

```
Searching in directory: C:\dev\ros2_humble
Processed 0 package(s), 0 message definition(s) total.
```

Seems a little unproductive?

**Comment by noelex** [comment] 2024-05-02 14:57
Well, [RobotecAI/ros2cs](https://github.com/RobotecAI/ros2cs) and rclnet(this repository) are totally unrelated, and they not supposed to work together.

If you are trying to use [RobotecAI/ros2cs](https://github.com/RobotecAI/ros2cs), you should follow its documentation and don’t need to install rclnet.

If you are using rclnet, then you don’t need to clone [RobotecAI/ros2cs](https://github.com/RobotecAI/ros2cs). You will need a valid ROS2 installation instead.

**Comment by sedwick2048** [comment] 2024-05-02 15:05
I have a valid ROS2 Humble installation; I can get a talker and listener communicating with each other in separate admin cmd windows.  My ultimate goal is to have a class library I can make part of my .NET project so I can instantiate classes that facilitate ROS2 communication.  I hit a wall with RobotecAI/ros2cs so I'm trying rclnet as well.  I'm just trying to follow directions.  Maybe I'm still confused on the fundamentals of how to create ROS2 code content?  But I'm at a loss for good info on that too.

**Comment by noelex** [comment] 2024-05-02 15:27
Are you using ROS2 installed in `C:\dev\ros2_humble`? Could you please run `ros2 pkg list` and `ros2 interface list` to show available packages and interfaces?

**Comment by sedwick2048** [comment] 2024-05-02 15:31
**Packages:**
action_msgs
action_tutorials_cpp
action_tutorials_interfaces
action_tutorials_py
actionlib_msgs
ament_clang_format
ament_clang_tidy
ament_cmake
ament_cmake_auto
ament_cmake_clang_format
ament_cmake_clang_tidy
ament_cmake_copyright
ament_cmake_core
ament_cmake_cppcheck
ament_cmake_cpplint
ament_cmake_export_assemblies
ament_cmake_export_definitions
ament_cmake_export_dependencies
ament_cmake_export_include_directories
ament_cmake_export_interfaces
ament_cmake_export_libraries
ament_cmake_export_link_flags
ament_cmake_export_targets
ament_cmake_flake8
ament_cmake_gen_version_h
ament_cmake_gmock
ament_cmake_google_benchmark
ament_cmake_gtest
ament_cmake_include_directories
ament_cmake_libraries
ament_cmake_lint_cmake
ament_cmake_mypy
ament_cmake_nose
ament_cmake_pclint
ament_cmake_pep257
ament_cmake_pycodestyle
ament_cmake_pyflakes
ament_cmake_pytest
ament_cmake_python
ament_cmake_ros
ament_cmake_target_dependencies
ament_cmake_test
ament_cmake_uncrustify
ament_cmake_vendor_package
ament_cmake_version
ament_cmake_xmllint
ament_copyright
ament_cppcheck
ament_cpplint
ament_flake8
ament_index_cpp
ament_index_python
ament_lint
ament_lint_auto
ament_lint_cmake
ament_lint_common
ament_mypy
ament_package
ament_pclint
ament_pep257
ament_pycodestyle
ament_pyflakes
ament_uncrustify
ament_xmllint
builtin_interfaces
camera_calibration_parsers
camera_info_manager
class_loader
common_interfaces
composition
composition_interfaces
console_bridge_vendor
demo_nodes_cpp
demo_nodes_cpp_native
demo_nodes_py
diagnostic_msgs
domain_coordinator
dotnet_cmake_module
dummy_map_server
dummy_robot_bringup
dummy_sensors
eigen3_cmake_module
example_interfaces
examples_rclcpp_async_client
examples_rclcpp_cbg_executor
examples_rclcpp_minimal_action_client
examples_rclcpp_minimal_action_server
examples_rclcpp_minimal_client
examples_rclcpp_minimal_composition
examples_rclcpp_minimal_publisher
examples_rclcpp_minimal_service
examples_rclcpp_minimal_subscriber
examples_rclcpp_minimal_timer
examples_rclcpp_multithreaded_executor
examples_rclcpp_wait_set
examples_rclpy_executors
examples_rclpy_guard_conditions
examples_rclpy_minimal_action_client
examples_rclpy_minimal_action_server
examples_rclpy_minimal_client
examples_rclpy_minimal_publisher
examples_rclpy_minimal_service
examples_rclpy_minimal_subscriber
examples_rclpy_pointcloud_publisher
examples_tf2_py
fastrtps_cmake_module
geometry2
geometry_msgs
image_common
image_tools
image_transport
interactive_markers
intra_process_demo
kdl_parser
keyboard_handler
laser_geometry
launch
launch_pytest
launch_ros
launch_testing
launch_testing_ament_cmake
launch_testing_examples
launch_testing_ros
launch_xml
launch_yaml
libcurl_vendor
libstatistics_collector
libyaml_vendor
lifecycle
lifecycle_msgs
lifecycle_py
logging_demo
map_msgs
mcap_vendor
message_filters
mimick_vendor
nav_msgs
orocos_kdl_vendor
osrf_pycommon
pendulum_msgs
performance_test_fixture
pluginlib
pybind11_vendor
python_cmake_module
python_orocos_kdl_vendor
python_qt_binding
qt_dotgraph
qt_gui
qt_gui_app
qt_gui_core
qt_gui_cpp
qt_gui_py_common
quality_of_service_demo_cpp
quality_of_service_demo_py
rcl
rcl_action
rcl_interfaces
rcl_lifecycle
rcl_logging_interface
rcl_logging_noop
rcl_logging_spdlog
rcl_yaml_param_parser
rclcpp
rclcpp_action
rclcpp_components
rclcpp_lifecycle
rclpy
rcpputils
rcutils
resource_retriever
rmw
rmw_connextdds
rmw_connextdds_common
rmw_connextddsmicro
rmw_cyclonedds_cpp
rmw_dds_common
rmw_fastrtps_cpp
rmw_fastrtps_dynamic_cpp
rmw_fastrtps_shared_cpp
rmw_implementation
rmw_implementation_cmake
robot_state_publisher
ros2action
ros2bag
ros2cli
ros2cli_common_extensions
ros2cli_test_interfaces
ros2component
ros2cs_common
ros2cs_core
ros2doctor
ros2interface
ros2launch
ros2lifecycle
ros2lifecycle_test_fixtures
ros2multicast
ros2node
ros2param
ros2pkg
ros2run
ros2service
ros2test
ros2topic
ros2trace
ros_environment
ros_testing
rosbag2
rosbag2_compression
rosbag2_compression_zstd
rosbag2_cpp
rosbag2_interfaces
rosbag2_performance_benchmarking
rosbag2_py
rosbag2_storage
rosbag2_storage_default_plugins
rosbag2_storage_mcap
rosbag2_storage_mcap_testdata
rosbag2_test_common
rosbag2_tests
rosbag2_transport
rosgraph_msgs
rosidl_adapter
rosidl_cli
rosidl_cmake
rosidl_default_generators
rosidl_default_runtime
rosidl_generator_c
rosidl_generator_cpp
rosidl_generator_cs
rosidl_generator_dds_idl
rosidl_generator_py
rosidl_parser
rosidl_runtime_c
rosidl_runtime_cpp
rosidl_runtime_py
rosidl_typesupport_c
rosidl_typesupport_cpp
rosidl_typesupport_fastrtps_c
rosidl_typesupport_fastrtps_cpp
rosidl_typesupport_interface
rosidl_typesupport_introspection_c
rosidl_typesupport_introspection_cpp
rosidl_typesupport_introspection_tests
rpyutils
rqt
rqt_action
rqt_bag
rqt_bag_plugins
rqt_console
rqt_graph
rqt_gui
rqt_gui_cpp
rqt_gui_py
rqt_msg
rqt_plot
rqt_publisher
rqt_py_common
rqt_py_console
rqt_reconfigure
rqt_service_caller
rqt_shell
rqt_srv
rqt_topic
rti_connext_dds_cmake_module
rviz2
rviz_assimp_vendor
rviz_common
rviz_default_plugins
rviz_ogre_vendor
rviz_rendering
rviz_rendering_tests
rviz_visual_testing_framework
sensor_msgs
sensor_msgs_py
shape_msgs
shared_queues_vendor
spdlog_vendor
sqlite3_vendor
sros2
sros2_cmake
statistics_msgs
std_msgs
std_srvs
stereo_msgs
tango_icons_vendor
test_cli
test_cli_remapping
test_communication
test_interface_files
test_launch_ros
test_launch_testing
test_msgs
test_quality_of_service
test_rclcpp
test_rmw_implementation
test_security
test_tf2
test_tracetools
test_tracetools_launch
tf2
tf2_bullet
tf2_eigen
tf2_eigen_kdl
tf2_geometry_msgs
tf2_kdl
tf2_msgs
tf2_py
tf2_ros
tf2_ros_py
tf2_sensor_msgs
tf2_tools
tinyxml2_vendor
tinyxml_vendor
topic_monitor
topic_statistics_demo
tracetools
tracetools_launch
tracetools_read
tracetools_test
tracetools_trace
trajectory_msgs
turtlesim
uncrustify_vendor
unique_identifier_msgs
urdf
urdf_parser_plugin
visualization_msgs
yaml_cpp_vendor
zstd_vendor

**Interfaces:**
Messages:
    action_msgs/msg/GoalInfo
    action_msgs/msg/GoalStatus
    action_msgs/msg/GoalStatusArray
    actionlib_msgs/msg/GoalID
    actionlib_msgs/msg/GoalStatus
    actionlib_msgs/msg/GoalStatusArray
    builtin_interfaces/msg/Duration
    builtin_interfaces/msg/Time
    diagnostic_msgs/msg/DiagnosticArray
    diagnostic_msgs/msg/DiagnosticStatus
    diagnostic_msgs/msg/KeyValue
    example_interfaces/msg/Bool
    example_interfaces/msg/Byte
    example_interfaces/msg/ByteMultiArray
    example_interfaces/msg/Char
    example_interfaces/msg/Empty
    example_interfaces/msg/Float32
    example_interfaces/msg/Float32MultiArray
    example_interfaces/msg/Float64
    example_interfaces/msg/Float64MultiArray
    example_interfaces/msg/Int16
    example_interfaces/msg/Int16MultiArray
    example_interfaces/msg/Int32
    example_interfaces/msg/Int32MultiArray
    example_interfaces/msg/Int64
    example_interfaces/msg/Int64MultiArray
    example_interfaces/msg/Int8
    example_interfaces/msg/Int8MultiArray
    example_interfaces/msg/MultiArrayDimension
    example_interfaces/msg/MultiArrayLayout
    example_interfaces/msg/String
    example_interfaces/msg/UInt16
    example_interfaces/msg/UInt16MultiArray
    example_interfaces/msg/UInt32
    example_interfaces/msg/UInt32MultiArray
    example_interfaces/msg/UInt64
    example_interfaces/msg/UInt64MultiArray
    example_interfaces/msg/UInt8
    example_interfaces/msg/UInt8MultiArray
    example_interfaces/msg/WString
    geometry_msgs/msg/Accel
    geometry_msgs/msg/AccelStamped
    geometry_msgs/msg/AccelWithCovariance
    geometry_msgs/msg/AccelWithCovarianceStamped
    geometry_msgs/msg/Inertia
    geometry_msgs/msg/InertiaStamped
    geometry_msgs/msg/Point
    geometry_msgs/msg/Point32
    geometry_msgs/msg/PointStamped
    geometry_msgs/msg/Polygon
    geometry_msgs/msg/PolygonStamped
    geometry_msgs/msg/Pose
    geometry_msgs/msg/Pose2D
    geometry_msgs/msg/PoseArray
    geometry_msgs/msg/PoseStamped
    geometry_msgs/msg/PoseWithCovariance
    geometry_msgs/msg/PoseWithCovarianceStamped
    geometry_msgs/msg/Quaternion
    geometry_msgs/msg/QuaternionStamped
    geometry_msgs/msg/Transform
    geometry_msgs/msg/TransformStamped
    geometry_msgs/msg/Twist
    geometry_msgs/msg/TwistStamped
    geometry_msgs/msg/TwistWithCovariance
    geometry_msgs/msg/TwistWithCovarianceStamped
    geometry_msgs/msg/Vector3
    geometry_msgs/msg/Vector3Stamped
    geometry_msgs/msg/Wrench
    geometry_msgs/msg/WrenchStamped
    lifecycle_msgs/msg/State
    lifecycle_msgs/msg/Transition
    lifecycle_msgs/msg/TransitionDescription
    lifecycle_msgs/msg/TransitionEvent
    map_msgs/msg/OccupancyGridUpdate
    map_msgs/msg/PointCloud2Update
    map_msgs/msg/ProjectedMap
    map_msgs/msg/ProjectedMapInfo
    nav_msgs/msg/GridCells
    nav_msgs/msg/MapMetaData
    nav_msgs/msg/OccupancyGrid
    nav_msgs/msg/Odometry
    nav_msgs/msg/Path
    pendulum_msgs/msg/JointCommand
    pendulum_msgs/msg/JointState
    pendulum_msgs/msg/RttestResults
    rcl_interfaces/msg/FloatingPointRange
    rcl_interfaces/msg/IntegerRange
    rcl_interfaces/msg/ListParametersResult
    rcl_interfaces/msg/Log
    rcl_interfaces/msg/Parameter
    rcl_interfaces/msg/ParameterDescriptor
    rcl_interfaces/msg/ParameterEvent
    rcl_interfaces/msg/ParameterEventDescriptors
    rcl_interfaces/msg/ParameterType
    rcl_interfaces/msg/ParameterValue
    rcl_interfaces/msg/SetParametersResult
    rmw_dds_common/msg/Gid
    rmw_dds_common/msg/NodeEntitiesInfo
    rmw_dds_common/msg/ParticipantEntitiesInfo
    ros2cli_test_interfaces/msg/ShortVaried
    ros2cli_test_interfaces/msg/ShortVariedMultiNested
    ros2cli_test_interfaces/msg/ShortVariedNested
    rosbag2_interfaces/msg/ReadSplitEvent
    rosbag2_interfaces/msg/WriteSplitEvent
    rosbag2_storage_mcap_testdata/msg/BasicIdl
    rosbag2_storage_mcap_testdata/msg/BasicMsg
    rosbag2_storage_mcap_testdata/msg/ComplexIdl
    rosbag2_storage_mcap_testdata/msg/ComplexMsg
    rosbag2_storage_mcap_testdata/msg/ComplexMsgDependsOnIdl
    rosgraph_msgs/msg/Clock
    sensor_msgs/msg/BatteryState
    sensor_msgs/msg/CameraInfo
    sensor_msgs/msg/ChannelFloat32
    sensor_msgs/msg/CompressedImage
    sensor_msgs/msg/FluidPressure
    sensor_msgs/msg/Illuminance
    sensor_msgs/msg/Image
    sensor_msgs/msg/Imu
    sensor_msgs/msg/JointState
    sensor_msgs/msg/Joy
    sensor_msgs/msg/JoyFeedback
    sensor_msgs/msg/JoyFeedbackArray
    sensor_msgs/msg/LaserEcho
    sensor_msgs/msg/LaserScan
    sensor_msgs/msg/MagneticField
    sensor_msgs/msg/MultiDOFJointState
    sensor_msgs/msg/MultiEchoLaserScan
    sensor_msgs/msg/NavSatFix
    sensor_msgs/msg/NavSatStatus
    sensor_msgs/msg/PointCloud
    sensor_msgs/msg/PointCloud2
    sensor_msgs/msg/PointField
    sensor_msgs/msg/Range
    sensor_msgs/msg/RegionOfInterest
    sensor_msgs/msg/RelativeHumidity
    sensor_msgs/msg/Temperature
    sensor_msgs/msg/TimeReference
    shape_msgs/msg/Mesh
    shape_msgs/msg/MeshTriangle
    shape_msgs/msg/Plane
    shape_msgs/msg/SolidPrimitive
    statistics_msgs/msg/MetricsMessage
    statistics_msgs/msg/StatisticDataPoint
    statistics_msgs/msg/StatisticDataType
    std_msgs/msg/Bool
    std_msgs/msg/Byte
    std_msgs/msg/ByteMultiArray
    std_msgs/msg/Char
    std_msgs/msg/ColorRGBA
    std_msgs/msg/Empty
    std_msgs/msg/Float32
    std_msgs/msg/Float32MultiArray
    std_msgs/msg/Float64
    std_msgs/msg/Float64MultiArray
    std_msgs/msg/Header
    std_msgs/msg/Int16
    std_msgs/msg/Int16MultiArray
    std_msgs/msg/Int32
    std_msgs/msg/Int32MultiArray
    std_msgs/msg/Int64
    std_msgs/msg/Int64MultiArray
    std_msgs/msg/Int8
    std_msgs/msg/Int8MultiArray
    std_msgs/msg/MultiArrayDimension
    std_msgs/msg/MultiArrayLayout
    std_msgs/msg/String
    std_msgs/msg/UInt16
    std_msgs/msg/UInt16MultiArray
    std_msgs/msg/UInt32
    std_msgs/msg/UInt32MultiArray
    std_msgs/msg/UInt64
    std_msgs/msg/UInt64MultiArray
    std_msgs/msg/UInt8
    std_msgs/msg/UInt8MultiArray
    stereo_msgs/msg/DisparityImage
    test_msgs/msg/Arrays
    test_msgs/msg/BasicTypes
    test_msgs/msg/BoundedPlainSequences
    test_msgs/msg/BoundedSequences
    test_msgs/msg/Builtins
    test_msgs/msg/Constants
    test_msgs/msg/Defaults
    test_msgs/msg/Empty
    test_msgs/msg/MultiNested
    test_msgs/msg/Nested
    test_msgs/msg/Strings
    test_msgs/msg/UnboundedSequences
    test_msgs/msg/WStrings
    tf2_msgs/msg/TF2Error
    tf2_msgs/msg/TFMessage
    trajectory_msgs/msg/JointTrajectory
    trajectory_msgs/msg/JointTrajectoryPoint
    trajectory_msgs/msg/MultiDOFJointTrajectory
    trajectory_msgs/msg/MultiDOFJointTrajectoryPoint
    turtlesim/msg/Color
    turtlesim/msg/Pose
    unique_identifier_msgs/msg/UUID
    visualization_msgs/msg/ImageMarker
    visualization_msgs/msg/InteractiveMarker
    visualization_msgs/msg/InteractiveMarkerControl
    visualization_msgs/msg/InteractiveMarkerFeedback
    visualization_msgs/msg/InteractiveMarkerInit
    visualization_msgs/msg/InteractiveMarkerPose
    visualization_msgs/msg/InteractiveMarkerUpdate
    visualization_msgs/msg/Marker
    visualization_msgs/msg/MarkerArray
    visualization_msgs/msg/MenuEntry
    visualization_msgs/msg/MeshFile
    visualization_msgs/msg/UVCoordinate
Services:
    action_msgs/srv/CancelGoal
    composition_interfaces/srv/ListNodes
    composition_interfaces/srv/LoadNode
    composition_interfaces/srv/UnloadNode
    diagnostic_msgs/srv/AddDiagnostics
    diagnostic_msgs/srv/SelfTest
    example_interfaces/srv/AddTwoInts
    example_interfaces/srv/SetBool
    example_interfaces/srv/Trigger
    lifecycle_msgs/srv/ChangeState
    lifecycle_msgs/srv/GetAvailableStates
    lifecycle_msgs/srv/GetAvailableTransitions
    lifecycle_msgs/srv/GetState
    logging_demo/srv/ConfigLogger
    map_msgs/srv/GetMapROI
    map_msgs/srv/GetPointMap
    map_msgs/srv/GetPointMapROI
    map_msgs/srv/ProjectedMapsInfo
    map_msgs/srv/SaveMap
    map_msgs/srv/SetMapProjections
    nav_msgs/srv/GetMap
    nav_msgs/srv/GetPlan
    nav_msgs/srv/LoadMap
    nav_msgs/srv/SetMap
    rcl_interfaces/srv/DescribeParameters
    rcl_interfaces/srv/GetParameterTypes
    rcl_interfaces/srv/GetParameters
    rcl_interfaces/srv/ListParameters
    rcl_interfaces/srv/SetParameters
    rcl_interfaces/srv/SetParametersAtomically
    ros2cli_test_interfaces/srv/ShortVariedMultiNested
    rosbag2_interfaces/srv/Burst
    rosbag2_interfaces/srv/GetRate
    rosbag2_interfaces/srv/IsPaused
    rosbag2_interfaces/srv/Pause
    rosbag2_interfaces/srv/PlayNext
    rosbag2_interfaces/srv/Resume
    rosbag2_interfaces/srv/Seek
    rosbag2_interfaces/srv/SetRate
    rosbag2_interfaces/srv/Snapshot
    rosbag2_interfaces/srv/TogglePaused
    rosbag2_storage_mcap_testdata/srv/BasicSrv
    sensor_msgs/srv/SetCameraInfo
    std_srvs/srv/Empty
    std_srvs/srv/SetBool
    std_srvs/srv/Trigger
    test_msgs/srv/Arrays
    test_msgs/srv/BasicTypes
    test_msgs/srv/Empty
    tf2_msgs/srv/FrameGraph
    turtlesim/srv/Kill
    turtlesim/srv/SetPen
    turtlesim/srv/Spawn
    turtlesim/srv/TeleportAbsolute
    turtlesim/srv/TeleportRelative
    visualization_msgs/srv/GetInteractiveMarkers
Actions:
    action_tutorials_interfaces/action/Fibonacci
    example_interfaces/action/Fibonacci
    ros2cli_test_interfaces/action/ShortVariedMultiNested
    rosbag2_storage_mcap_testdata/action/BasicAction
    test_msgs/action/Fibonacci
    test_msgs/action/NestedMessage
    tf2_msgs/action/LookupTransform
    turtlesim/action/RotateAbsolute

**Comment by noelex** [comment] 2024-05-02 15:38
Now try running ros2cs with the same command prompt?

**Comment by sedwick2048** [comment] 2024-05-02 15:43
Like I just did?

```
C:\dev\SimpleROS2dotNET\SimpleROS2dotNET\SimpleROS2dotNET>ros2cs ros2cs.spec
Searching in directory: C:\dev\ros2_humble

Processed 0 package(s), 0 message definition(s) total.
```

**Comment by noelex** [comment] 2024-05-02 15:45
Oh please also change `from-directory C:\dev\ros2_humble` to `from-directory C:\dev\ros2_humble\share`

**Comment by sedwick2048** [comment] 2024-05-02 15:46
```
C:\dev\SimpleROS2dotNET\SimpleROS2dotNET\SimpleROS2dotNET>ros2cs ros2cs.spec
Searching in directory: C:\dev\ros2_humble\share.
Unable to parse field defined as 'FieldDeclaration { Type = bool, Identifier = BOOL_CONST, Value = true , IsArray = False, ArrayLength = , InlineComment = Comment - Nesting Level 1: 1 of 2, IsUpperBounded = False }': Invalid constant value type 'bool'.
```

**Comment by noelex** [comment] 2024-05-02 15:58
Please also  add `exclude test_msgs` to `ros2cs.spec`.

**Comment by sedwick2048** [comment] 2024-05-02 16:02
Same exact results.

**Comment by noelex** [comment] 2024-05-02 16:17
Well, there’s nothing else I can do then. I’m not aware of any other package which defines `BOOL_CONST`.

One last thing to try is to only include packages which you want to use, e.g. `include geometry_msgs sensor_msgs`. This should work for most situations because default value of arrays and constant Boolean values are typically not used by well-known ROS messages.

I will address these issues in a later release when I have time.

**Comment by sedwick2048** [comment] 2024-05-02 22:23
For what it's worth, I found BOOL_CONST in these files:

C:\Dev\ros2_humble\share\ros2cli_test_interfaces\msg\ShortVaried.msg
```
# A constant
bool BOOL_CONST=true # Comment - Nesting Level 1: 1 of 2

# Bool and array of bools
bool bool_value
bool[<=3] bool_values # Comment - Nesting Level 1: 2 of 2
```

C:\Dev\ros2_humble\share\test_interface_files\msg\Constants.msg
C:\Dev\ros2_humble\share\test_msgs\msg\Constants.msg
```
bool BOOL_CONST=true
byte BYTE_CONST=50
char CHAR_CONST=100
float32 FLOAT32_CONST=1.125
float64 FLOAT64_CONST=1.125
int8 INT8_CONST=-50
uint8 UINT8_CONST=200
int16 INT16_CONST=-1000
uint16 UINT16_CONST=2000
int32 INT32_CONST=-30000
uint32 UINT32_CONST=60000
int64 INT64_CONST=-40000000
uint64 UINT64_CONST=50000000
```

I guess I'll do more research into how this whole "ROS2 in .NET" thing works and figure out what packages I even want to use.

**Comment by noelex** [comment] 2024-05-06 07:52
The bug is fixed in v1.3.1. Please update ros2cs utility and see if it can generate messages for you now.

Feel free to reopen if you have further questions.

**Comment by noelex** [comment] 2024-05-07 02:03
Looks like this is caused by inline comments in [ros2cli_test_interfaces/ShortVaried.msg](https://github.com/ros2/ros2cli/blob/rolling/ros2cli_test_interfaces/msg/ShortVaried.msg). Could you please update ros2cs and try again?

**Comment by sedwick2048** [comment] 2024-05-07 14:10
```
C:\dev\ros2_dotNET_ws2>dotnet tool install -g ros2cs
Tool 'ros2cs' was successfully updated from version '1.3.1' to version '1.3.2'.

C:\dev\ros2_dotNET_ws2>ros2cs C:\dev\SimpleROS2dotNET\SimpleROS2dotNET\SimpleROS2dotNET\ros2cs.spec
Searching in directory: C:\dev\ros2_humble\share.
Converting actionlib_msgs/msg/GoalID to C:\dev\SimpleROS2dotNET\SimpleROS2dotNET\SimpleROS2dotNET\Actionlib\Messages\GoalID.cs ...
[200+ messages like that...]
Converting visualization_msgs/srv/GetInteractiveMarkers to C:\dev\SimpleROS2dotNET\SimpleROS2dotNET\SimpleROS2dotNET\Visualization\Services\GetInteractiveMarkers.cs ...

Processed 30 package(s), 253 message definition(s) total.
```

So, progress!  I'm currently attempting the building of a package, I'll see what happens when apply this stuff to it.  Thanks!

**Closed** 2024-05-07 15:21 UTC
